[package]
name = "overpower"
version = "0.1.0"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.32"
reqwest = "0.9"
structopt = "0.2"
tokio = "0.1"
futures = "0.1"
